In [3]:
#Multiple Linear Regression
#y = b0 + b1*x1 + b2*x2+----+bn*xn

In [46]:
#Assumtions of linear regression-
#Linearity,
#Homoscedasticity,
#Multivariate normality,
#Independence of errors,
#Lack of multicollinearity
#5 methods of building model-
#All-in
#Backward Eliination
#Forward Selection
#Bidirectional Elimination
#Score comparison

In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
dataset = pd.read_csv("50_Startups.csv")

In [48]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [80]:
#State is having catagorical data
#Dummy variables~New York and California
#We won't include both the dummy variables as D2=1-D1 ~ Dummy variable trap
#Always omit one dummy variable(We can have only one dummy variable in our model)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
y = y.astype(int)

In [81]:
y

array([192261, 191792, 191050, 182901, 166187, 156991, 156122, 155752,
       152211, 149759, 146121, 144259, 141585, 134307, 132602, 129917,
       126992, 125370, 124266, 122776, 118474, 111313, 110352, 108733,
       108552, 107404, 105733, 105008, 103282, 101004,  99937,  97483,
        97427,  96778,  96712,  96479,  90708,  89949,  81229,  81005,
        78239,  77798,  71498,  69758,  65200,  64926,  49490,  42559,
        35673,  14681])

In [82]:
#for state column, we'll use onehotencoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder_X = OneHotEncoder(categorical_features = [3])
X = onehotencoder_X.fit_transform(X).toarray()

In [83]:
X = X.astype(int)
X

array([[     0,      0,      1, 165349, 136897, 471784],
       [     1,      0,      0, 162597, 151377, 443898],
       [     0,      1,      0, 153441, 101145, 407934],
       [     0,      0,      1, 144372, 118671, 383199],
       [     0,      1,      0, 142107,  91391, 366168],
       [     0,      0,      1, 131876,  99814, 362861],
       [     1,      0,      0, 134615, 147198, 127716],
       [     0,      1,      0, 130298, 145530, 323876],
       [     0,      0,      1, 120542, 148718, 311613],
       [     1,      0,      0, 123334, 108679, 304981],
       [     0,      1,      0, 101913, 110594, 229160],
       [     1,      0,      0, 100671,  91790, 249744],
       [     0,      1,      0,  93863, 127320, 249839],
       [     1,      0,      0,  91992, 135495, 252664],
       [     0,      1,      0, 119943, 156547, 256512],
       [     0,      0,      1, 114523, 122616, 261776],
       [     1,      0,      0,  78013, 121597, 264346],
       [     0,      0,      1,

In [84]:
#Avoiding the dummy variable trap
X = X[:, 1:]

In [85]:
X

array([[     0,      1, 165349, 136897, 471784],
       [     0,      0, 162597, 151377, 443898],
       [     1,      0, 153441, 101145, 407934],
       [     0,      1, 144372, 118671, 383199],
       [     1,      0, 142107,  91391, 366168],
       [     0,      1, 131876,  99814, 362861],
       [     0,      0, 134615, 147198, 127716],
       [     1,      0, 130298, 145530, 323876],
       [     0,      1, 120542, 148718, 311613],
       [     0,      0, 123334, 108679, 304981],
       [     1,      0, 101913, 110594, 229160],
       [     0,      0, 100671,  91790, 249744],
       [     1,      0,  93863, 127320, 249839],
       [     0,      0,  91992, 135495, 252664],
       [     1,      0, 119943, 156547, 256512],
       [     0,      1, 114523, 122616, 261776],
       [     0,      0,  78013, 121597, 264346],
       [     0,      1,  94657, 145077, 282574],
       [     1,      0,  91749, 114175, 294919],
       [     0,      1,  86419, 153514,      0],
       [     0,     

In [86]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [87]:
X_train

array([[     1,      0,  55493, 103057, 214634],
       [     0,      1,  46014,  85047, 205517],
       [     1,      0,  75328, 144135, 134050],
       [     0,      0,  46426, 157693, 210797],
       [     1,      0,  91749, 114175, 294919],
       [     1,      0, 130298, 145530, 323876],
       [     1,      0, 119943, 156547, 256512],
       [     0,      1,   1000, 124153,   1903],
       [     0,      1,    542,  51743,      0],
       [     0,      1,  65605, 153032, 107138],
       [     0,      1, 114523, 122616, 261776],
       [     1,      0,  61994, 115641,  91131],
       [     0,      0,  63408, 129219,  46085],
       [     0,      0,  78013, 121597, 264346],
       [     0,      0,  23640,  96189, 148001],
       [     0,      0,  76253, 113867, 298664],
       [     0,      1,  15505, 127382,  35534],
       [     0,      1, 120542, 148718, 311613],
       [     0,      0,  91992, 135495, 252664],
       [     0,      0,  64664, 139553, 137962],
       [     0,     

In [57]:
y_train

array([ 96778,  96479, 105733,  96712, 124266, 155752, 132602,  64926,
        35673, 101004, 129917,  99937,  97427, 126992,  71498, 118474,
        69758, 152211, 134307, 107404, 156991, 125370,  78239,  14681,
       191792, 141585,  89949, 108552, 156122, 108733,  90708, 111313,
       122776, 149759,  81005,  49490, 182901, 192261,  42559,  65200])

In [58]:
X_test

array([[     1,      0,  66051, 182645, 118148],
       [     0,      0, 100671,  91790, 249744],
       [     1,      0, 101913, 110594, 229160],
       [     1,      0,  27892,  84710, 164470],
       [     1,      0, 153441, 101145, 407934],
       [     0,      1,  72107, 127864, 353183],
       [     0,      1,  20229,  65947, 185265],
       [     0,      1,  61136, 152701,  88218],
       [     1,      0,  73994, 122782, 303319],
       [     1,      0, 142107,  91391, 366168]])

In [59]:
y_test

array([103282, 144259, 146121,  77798, 191050, 105008,  81229,  97483,
       110352, 166187])

In [60]:
#feature scaling will be done by multiple linear regression library itself
#fitting multiple linear regression to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [61]:
#predicting the test set results
y_pred = regressor.predict(X_test)

In [62]:
y_pred

array([103014.53150229, 132581.41936035, 132447.42482198,  71975.10622804,
       178536.86756353, 116160.60279589,  67851.05366532,  98791.23634391,
       113968.75756885, 167920.57416969])

In [63]:
y_test

array([103282, 144259, 146121,  77798, 191050, 105008,  81229,  97483,
       110352, 166187])

In [88]:
#To have only those independent variables that have much more significance and to eliminate all those with negligieble significance, we'll use  backward elimination method
#Building the optimal model using Backward Elimination
import statsmodels.formula.api as sm
#we need to add one column x0 to the dataset for b0(constant) and value of x0 = 1
#X = np.append(arr = X, values = np.ones((50, 1)).astype(int), axis = 1) #axis  = 1 for adding column and axis = 0 for adding line
#it'll append all the ones in last

In [89]:
X

array([[     0,      1, 165349, 136897, 471784],
       [     0,      0, 162597, 151377, 443898],
       [     1,      0, 153441, 101145, 407934],
       [     0,      1, 144372, 118671, 383199],
       [     1,      0, 142107,  91391, 366168],
       [     0,      1, 131876,  99814, 362861],
       [     0,      0, 134615, 147198, 127716],
       [     1,      0, 130298, 145530, 323876],
       [     0,      1, 120542, 148718, 311613],
       [     0,      0, 123334, 108679, 304981],
       [     1,      0, 101913, 110594, 229160],
       [     0,      0, 100671,  91790, 249744],
       [     1,      0,  93863, 127320, 249839],
       [     0,      0,  91992, 135495, 252664],
       [     1,      0, 119943, 156547, 256512],
       [     0,      1, 114523, 122616, 261776],
       [     0,      0,  78013, 121597, 264346],
       [     0,      1,  94657, 145077, 282574],
       [     1,      0,  91749, 114175, 294919],
       [     0,      1,  86419, 153514,      0],
       [     0,     

In [90]:
#to append all the ones at begining
X =  np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)

In [91]:
X

array([[     1,      0,      1, 165349, 136897, 471784],
       [     1,      0,      0, 162597, 151377, 443898],
       [     1,      1,      0, 153441, 101145, 407934],
       [     1,      0,      1, 144372, 118671, 383199],
       [     1,      1,      0, 142107,  91391, 366168],
       [     1,      0,      1, 131876,  99814, 362861],
       [     1,      0,      0, 134615, 147198, 127716],
       [     1,      1,      0, 130298, 145530, 323876],
       [     1,      0,      1, 120542, 148718, 311613],
       [     1,      0,      0, 123334, 108679, 304981],
       [     1,      1,      0, 101913, 110594, 229160],
       [     1,      0,      0, 100671,  91790, 249744],
       [     1,      1,      0,  93863, 127320, 249839],
       [     1,      0,      0,  91992, 135495, 252664],
       [     1,      1,      0, 119943, 156547, 256512],
       [     1,      0,      1, 114523, 122616, 261776],
       [     1,      0,      0,  78013, 121597, 264346],
       [     1,      0,      1,

In [92]:
X_opt = X[:,[0,1,2,3,4,5]]
#OLS~Ordinary Least Square
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()

In [ ]:
#Steps for Backward Elimination-
#step1-selct a significance level to stay in the model(SL = 0.05)
#step2-fill the full model with all possible predictors
#step3-consider the predictor with the highest P-value. If P>SL, go to step4, otherwise model is ready
#step4-fit model without this variable

In [93]:
#Implementing step3(P-value is probabaility)
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Mon, 31 Dec 2018   Prob (F-statistic):           1.34e-27
Time:                        16:04:24   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.836      7.281      0.000    3.62e+04     6.4e+04
x1           198.6230   3371.017      0.059      0.953   -6595.216    6992.462
x2           -41.9213   3256.050     -0.013      0.990   -6604.059    6520.216
x3             0.8060      0.046     17.368      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.783   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.267
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [95]:
#As x2 is having highest p value which is greater than SL, we'll remove it and again fit the model with remaining variables
X_opt = X[:,[0,1,3,4,5]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Mon, 31 Dec 2018   Prob (F-statistic):           8.49e-29
Time:                        16:09:26   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.884      7.537      0.000    3.67e+04    6.35e+04
x1           220.0101   2900.545      0.076      0.940   -5621.987    6062.008
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.759   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.173
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [99]:
X_opt = X[:,[0,3,4,5]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Mon, 31 Dec 2018   Prob (F-statistic):           4.53e-30
Time:                        16:13:24   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.366      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.839   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.443
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.587   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [100]:
X_opt = X[:,[0,3,5]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()
#As we can see adjusted R-squared increases, theresfore it's a better model

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Mon, 31 Dec 2018   Prob (F-statistic):           2.16e-31
Time:                        16:18:48   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.934     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.265      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.162
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [101]:
X_opt = X[:,[0,3]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()
#As we can see adjusted R-squared decreases, therefore it's not a better model

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Mon, 31 Dec 2018   Prob (F-statistic):           3.50e-32
Time:                        16:22:32   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.895     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.537
Skew:                          -0.911   Prob(JB):                     9.43e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [1]:
#So, model with independent variables having index 0, 3 and 5 is best model